# Generated by Django 4.1.6 on 2023-03-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_bookmark_like_reply_alter_feed_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='content_id',
            new_name='feed_id',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='content_id',
            new_name='feed_id',
        ),
    ]
