# Generated by Django 4.1.6 on 2023-03-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_content_id_bookmark_feed_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='like_count',
        ),
    ]
